version: '3'

services:
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - ./db:/data/db
